// Generated by scripts/compile_avm.cjs from avm.html. Do not edit directly.
const {
  useState,
  useMemo,
  useCallback,
  useRef,
  useEffect
} = React;
const API = "https://api.broquer.app";
const FC = {
  excelente: 1.0,
  bueno: 0.919,
  regular: 0.819,
  malo: 0.668
};
const CONSERV_OPTS = {
  excelente: "Excelente / Como nuevo",
  bueno: "Bueno",
  regular: "Regular / Necesita detalles",
  malo: "Malo / Necesita remodelación"
};
const CALIDAD_VRN = {
  lujo: 18500,
  bueno: 14000,
  medio: 11500,
  economico: 8500
};
const CALIDAD_OPTS = {
  lujo: "Lujo / Residencial plus",
  bueno: "Bueno / Residencial",
  medio: "Medio / Estándar",
  economico: "Económico / Interés social"
};
const TIPOS = [{
  id: "casa",
  label: "Casa",
  icon: ""
}, {
  id: "departamento",
  label: "Depto",
  icon: ""
}, {
  id: "terreno",
  label: "Terreno",
  icon: ""
}, {
  id: "local",
  label: "Local",
  icon: ""
}, {
  id: "oficina",
  label: "Oficina",
  icon: ""
}, {
  id: "bodega",
  label: "Bodega",
  icon: ""
}, {
  id: "edificio",
  label: "Edificio",
  icon: ""
}];
const CAMPOS = {
  casa: {
    terreno: true,
    construccion: true,
    recamaras: true,
    banos: true,
    estac: true,
    nivel: false,
    unidades: false,
    edad: true
  },
  departamento: {
    terreno: false,
    construccion: true,
    recamaras: true,
    banos: true,
    estac: true,
    nivel: true,
    unidades: false,
    edad: true
  },
  terreno: {
    terreno: true,
    construccion: false,
    recamaras: false,
    banos: false,
    estac: false,
    nivel: false,
    unidades: false,
    edad: false
  },
  local: {
    terreno: false,
    construccion: true,
    recamaras: false,
    banos: false,
    estac: true,
    nivel: true,
    unidades: false,
    edad: true
  },
  oficina: {
    terreno: false,
    construccion: true,
    recamaras: false,
    banos: false,
    estac: true,
    nivel: true,
    unidades: false,
    edad: true
  },
  bodega: {
    terreno: true,
    construccion: true,
    recamaras: false,
    banos: false,
    estac: true,
    nivel: false,
    unidades: false,
    edad: true
  },
  edificio: {
    terreno: true,
    construccion: true,
    recamaras: false,
    banos: false,
    estac: true,
    nivel: false,
    unidades: true,
    edad: true
  }
};
const fmt = n => "$" + Math.round(n || 0).toLocaleString("es-MX");
const pf = v => parseFloat(v) || 0;
function rossHeidecke(edad, vidaUtil, conservacion) {
  if (!vidaUtil || vidaUtil <= 0) return 1;
  const fc = FC[conservacion] || 1;
  return Math.max(0, Math.min(1, (1 - Math.pow(edad / vidaUtil, 1.4)) * fc));
}
function calcFactors(sujeto, comp) {
  const s = {
    m2c: pf(sujeto.m2Construccion),
    m2t: pf(sujeto.m2Terreno),
    edad: pf(sujeto.edad)
  };
  const c = {
    m2c: pf(comp.m2Construccion),
    m2t: pf(comp.m2Terreno),
    edad: pf(comp.edad)
  };
  const fNeg = 0.95;
  let fSup = 1.0;
  if (s.m2c > 0 && c.m2c > 0) {
    fSup = Math.pow(s.m2c / c.m2c, 0.25);
    fSup = Math.max(0.80, Math.min(1.25, fSup));
  }
  let fTC = 1.0;
  if (s.m2t > 0 && s.m2c > 0 && c.m2t > 0 && c.m2c > 0) {
    const rS = s.m2t / s.m2c,
      rC = c.m2t / c.m2c;
    if (rC > 0) {
      fTC = Math.pow(rS / rC, 0.15);
      fTC = Math.max(0.85, Math.min(1.20, fTC));
    }
  }
  let fEdad = 1.0;
  if (c.edad > 0 || s.edad > 0) {
    fEdad = 1 + (c.edad - s.edad) * 0.008;
    fEdad = Math.max(0.85, Math.min(1.20, fEdad));
  }
  const fZona = comp.mismaZona === "si" ? 1.0 : comp.mismaZona === "similar" ? 1.05 : 1.10;
  const consOrd = {
    excelente: 4,
    bueno: 3,
    regular: 2,
    malo: 1
  };
  const fCons = 1 + ((consOrd[comp.conservacion] || 3) - (consOrd[sujeto.conservacion] || 3)) * 0.05;
  const calOrd = {
    lujo: 4,
    bueno: 3,
    medio: 2,
    economico: 1
  };
  const fCal = 1 + ((calOrd[comp.calidad] || 2) - (calOrd[sujeto.calidad] || 2)) * 0.08;
  return {
    fNeg,
    fSup,
    fTC,
    fEdad,
    fZona,
    fCons,
    fCal,
    fResultante: fNeg * fSup * fTC * fEdad * fZona * fCons * fCal
  };
}
function F({
  label,
  children,
  flex = 1
}) {
  return /*#__PURE__*/React.createElement("div", {
    className: "field",
    style: {
      flex
    }
  }, /*#__PURE__*/React.createElement("label", null, label), children);
}
function NI({
  value,
  onChange,
  placeholder
}) {
  return /*#__PURE__*/React.createElement("input", {
    type: "number",
    inputMode: "decimal",
    value: value,
    placeholder: placeholder || "",
    onChange: e => onChange(e.target.value)
  });
}
function SI({
  value,
  onChange,
  options
}) {
  return /*#__PURE__*/React.createElement("select", {
    value: value,
    onChange: e => onChange(e.target.value)
  }, Object.entries(options).map(([k, v]) => /*#__PURE__*/React.createElement("option", {
    key: k,
    value: k
  }, v)));
}
function CompManualCard({
  comp,
  index,
  onChange,
  onRemove,
  sujeto
}) {
  const campos = CAMPOS[sujeto.tipo] || CAMPOS.casa;
  const vum = pf(comp.m2Construccion) > 0 ? pf(comp.precio) / pf(comp.m2Construccion) : 0;
  const factors = calcFactors(sujeto, comp);
  const vHomol = vum * factors.fResultante;
  return /*#__PURE__*/React.createElement("div", {
    className: "comp-manual-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "comp-manual-hdr"
  }, /*#__PURE__*/React.createElement("span", {
    className: "comp-num"
  }, "Comparable ", index + 1), /*#__PURE__*/React.createElement("button", {
    className: "btn-sm danger",
    onClick: onRemove
  }, "Quitar")), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Precio $",
    flex: 2
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.precio,
    onChange: v => onChange("precio", v),
    placeholder: "2,500,000"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, campos.construccion && /*#__PURE__*/React.createElement(F, {
    label: "m\xB2 construidos"
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.m2Construccion,
    onChange: v => onChange("m2Construccion", v),
    placeholder: "120"
  })), campos.terreno && /*#__PURE__*/React.createElement(F, {
    label: "m\xB2 terreno"
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.m2Terreno,
    onChange: v => onChange("m2Terreno", v),
    placeholder: "150"
  }))), (campos.recamaras || campos.banos || campos.estac) && /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, campos.recamaras && /*#__PURE__*/React.createElement(F, {
    label: "Rec\xE1maras"
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.recamaras,
    onChange: v => onChange("recamaras", v),
    placeholder: "3"
  })), campos.banos && /*#__PURE__*/React.createElement(F, {
    label: "Ba\xF1os"
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.banos,
    onChange: v => onChange("banos", v),
    placeholder: "2"
  })), campos.estac && /*#__PURE__*/React.createElement(F, {
    label: "Estac."
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.estacionamiento,
    onChange: v => onChange("estacionamiento", v),
    placeholder: "2"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Edad (a\xF1os)"
  }, /*#__PURE__*/React.createElement(NI, {
    value: comp.edad,
    onChange: v => onChange("edad", v),
    placeholder: "10"
  })), /*#__PURE__*/React.createElement(F, {
    label: "Estado"
  }, /*#__PURE__*/React.createElement(SI, {
    value: comp.conservacion,
    onChange: v => onChange("conservacion", v),
    options: CONSERV_OPTS
  }))), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Acabados"
  }, /*#__PURE__*/React.createElement(SI, {
    value: comp.calidad,
    onChange: v => onChange("calidad", v),
    options: CALIDAD_OPTS
  })), /*#__PURE__*/React.createElement(F, {
    label: "\xBFMisma zona?"
  }, /*#__PURE__*/React.createElement(SI, {
    value: comp.mismaZona,
    onChange: v => onChange("mismaZona", v),
    options: {
      si: "Sí",
      similar: "Cercana",
      diferente: "Diferente"
    }
  }))), vum > 0 && /*#__PURE__*/React.createElement("div", {
    className: "comp-price-m2"
  }, /*#__PURE__*/React.createElement("span", null, "Precio/m\xB2: ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "var(--ink)"
    }
  }, fmt(vum))), /*#__PURE__*/React.createElement("span", null, "Ajustado: ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "var(--warn)"
    }
  }, fmt(vHomol), "/m\xB2"))));
}
function ColoniaInput({
  value,
  onSelect,
  ciudad
}) {
  const [texto, setTexto] = useState(value ? value.nombre : "");
  const [sugerencias, setSugerencias] = useState([]);
  const [abierto, setAbierto] = useState(false);
  const [buscando, setBuscando] = useState(false);
  const timerRef = useRef(null);
  useEffect(() => {
    if (value) setTexto(value.nombre);
  }, [value]);
  const buscar = txt => {
    setTexto(txt);
    if (value) onSelect(null); // reset selection when typing
    clearTimeout(timerRef.current);
    if (txt.length < 3) {
      setSugerencias([]);
      setAbierto(false);
      return;
    }
    timerRef.current = setTimeout(async () => {
      setBuscando(true);
      try {
        const r = await fetch(`${API}/api/colonias?texto=${encodeURIComponent(txt)}&ciudad=${encodeURIComponent(ciudad || "")}`);
        const d = await r.json();
        setSugerencias(d.colonias || []);
        setAbierto(true);
      } catch {} finally {
        setBuscando(false);
      }
    }, 400);
  };
  const seleccionar = col => {
    setTexto(col.nombre);
    setSugerencias([]);
    setAbierto(false);
    onSelect(col);
  };
  if (value) {
    return /*#__PURE__*/React.createElement("div", {
      className: "colonia-selected"
    }, /*#__PURE__*/React.createElement("span", null, value.nombre), /*#__PURE__*/React.createElement("button", {
      onClick: () => {
        onSelect(null);
        setTexto("");
      }
    }, "\xD7"));
  }
  return /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-wrap"
  }, /*#__PURE__*/React.createElement("input", {
    type: "text",
    value: texto,
    onChange: e => buscar(e.target.value),
    placeholder: "Escribe la colonia...",
    style: {
      width: "100%",
      padding: "10px 12px",
      background: "var(--paper-2)",
      border: "1px solid rgba(0,0,0,0.1)",
      borderRadius: 10,
      color: "var(--ink)",
      outline: "none",
      fontFamily: "var(--font-sans)",
      fontSize: 14
    }
  }), buscando && /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 11,
      color: "var(--gray-400)",
      marginTop: 4
    }
  }, "Buscando..."), abierto && sugerencias.length > 0 && /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-dropdown"
  }, sugerencias.map((s, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    className: "autocomplete-item",
    onClick: () => seleccionar(s)
  }, /*#__PURE__*/React.createElement("div", {
    className: "ac-main"
  }, s.nombre), /*#__PURE__*/React.createElement("div", {
    className: "ac-sub"
  }, s.display)))), abierto && sugerencias.length === 0 && !buscando && texto.length >= 3 && /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-dropdown"
  }, /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-item",
    style: {
      color: "var(--gray-400)"
    }
  }, "Sin resultados \u2014 verifica el nombre")));
}

// ─── UBICACIÓN INPUT: colonia + ciudad + estado en una sola selección ──
// Antes había dos campos independientes (colonia con autocompletar, y
// ciudad como texto libre de una lista nacional sin relación con ningún
// estado). El estado ni siquiera se pedía — quedaba fijo en un default
// del backend. Resultado: combinaciones geográficamente imposibles como
// "Guadalajara, Michoacán". Ahora un solo campo busca la colonia en
// Google Places y cada sugerencia ya trae su ciudad y estado reales
// (ver routers/avm_places.py); al elegir una, los tres quedan fijados
// juntos y ya no se pueden desalinear.
function ColoniaTextInput({
  value,
  onChange,
  onSelect
}) {
  const [texto, setTexto] = useState(value || "");
  const [sugerencias, setSugerencias] = useState([]);
  const [abierto, setAbierto] = useState(false);
  const [buscando, setBuscando] = useState(false);
  const timerRef = useRef(null);
  useEffect(() => {
    setTexto(value || "");
  }, [value]);
  const onInput = e => {
    const v = e.target.value;
    setTexto(v);
    onChange(v);
    clearTimeout(timerRef.current);
    if (v.length < 3) {
      setSugerencias([]);
      setAbierto(false);
      return;
    }
    timerRef.current = setTimeout(async () => {
      setBuscando(true);
      try {
        const r = await fetch(`${API}/api/colonias?texto=${encodeURIComponent(v)}`);
        const d = await r.json();
        setSugerencias(d.colonias || []);
        setAbierto(true);
      } catch {} finally {
        setBuscando(false);
      }
    }, 400);
  };
  const seleccionar = col => {
    setTexto(col.nombre);
    setAbierto(false);
    onSelect(col);
  };
  return /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-wrap",
    onBlur: () => setTimeout(() => setAbierto(false), 150)
  }, /*#__PURE__*/React.createElement("input", {
    type: "text",
    value: texto,
    onChange: onInput,
    onFocus: () => texto.length >= 3 && sugerencias.length > 0 && setAbierto(true),
    placeholder: "Ej: Vistas Altozano, Morelia...",
    style: {
      width: "100%",
      padding: "10px 12px",
      background: "var(--paper-2)",
      border: "1px solid rgba(0,0,0,0.1)",
      borderRadius: 10,
      color: "var(--ink)",
      outline: "none",
      fontFamily: "var(--font-sans)",
      fontSize: 14
    }
  }), buscando && /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 11,
      color: "var(--gray-400)",
      marginTop: 4
    }
  }, "Buscando..."), abierto && sugerencias.length > 0 && /*#__PURE__*/React.createElement("div", {
    className: "autocomplete-dropdown"
  }, sugerencias.map((s, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    className: "autocomplete-item",
    onMouseDown: e => {
      e.preventDefault();
      seleccionar(s);
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "ac-main"
  }, s.nombre), s.display && /*#__PURE__*/React.createElement("div", {
    className: "ac-sub"
  }, s.display)))));
}

// ─── COMPONENTE IA WEB SEARCH ───────────────────────────────
function AvmIA() {
  const [form, setForm] = React.useState({
    tipo: "terreno",
    operacion: "venta",
    colonia: "",
    ciudad: "",
    estado: "",
    latitud: 0,
    longitud: 0,
    m2_terreno: "",
    m2_construccion: "",
    recamaras: "",
    banos: "",
    estacionamientos: "",
    condicion_terreno: "plano",
    comentarios: ""
  });
  const [estado, setEstado] = React.useState("idle"); // idle | loading | result | error
  const [resultado, setResultado] = React.useState(null);
  const [errorMsg, setErrorMsg] = React.useState("");
  const [pdfLoading, setPdfLoading] = React.useState(false);
  const [opinionMode, setOpinionMode] = React.useState(false);
  const [opFields, setOpFields] = React.useState({
    solicitante: "",
    empresa: "",
    expediente: "",
    valuador: "",
    cedula: "",
    observaciones: "",
    resumen: null,
    analisisZona: null,
    conclusiones: null
  });
  const uof = (k, v) => setOpFields(p => ({
    ...p,
    [k]: v
  }));
  const u = (k, v) => setForm(p => ({
    ...p,
    [k]: v
  }));
  const esTerreno = form.tipo === "terreno" || form.tipo === "edificio";
  const esConstruccion = ["casa", "departamento", "local", "oficina", "bodega", "edificio"].includes(form.tipo);

  // Expone __avmIAFill para que Broq pueda activar la pestaña IA con datos precargados
  React.useEffect(() => {
    window.__avmIAFill = data => {
      if (data.tipo_inmueble) setForm(p => ({
        ...p,
        tipo: data.tipo_inmueble
      }));
      if (data.colonia) setForm(p => ({
        ...p,
        colonia: data.colonia
      }));
      if (data.ciudad) setForm(p => ({
        ...p,
        ciudad: data.ciudad
      }));
      if (data.estado) setForm(p => ({
        ...p,
        estado: data.estado
      }));
      if (data.latitud) setForm(p => ({
        ...p,
        latitud: data.latitud
      }));
      if (data.longitud) setForm(p => ({
        ...p,
        longitud: data.longitud
      }));
      if (data.m2_terreno) setForm(p => ({
        ...p,
        m2_terreno: String(data.m2_terreno)
      }));
      if (data.m2_construccion) setForm(p => ({
        ...p,
        m2_construccion: String(data.m2_construccion)
      }));
      if (data.recamaras) setForm(p => ({
        ...p,
        recamaras: String(data.recamaras)
      }));
      if (data.banos) setForm(p => ({
        ...p,
        banos: String(data.banos)
      }));
      if (data.condicion_terreno) setForm(p => ({
        ...p,
        condicion_terreno: data.condicion_terreno
      }));
      if (data.operacion) setForm(p => ({
        ...p,
        operacion: data.operacion
      }));
    };
    const onMsg = e => {
      if (e.data && e.data.tipo === "opinion_valor_web") {
        window.__avmIAFill(e.data);
        // Auto-ejecutar la búsqueda
        setTimeout(() => {
          document.getElementById("btn-analizar-ia") && document.getElementById("btn-analizar-ia").click();
        }, 300);
      }
    };
    window.addEventListener("message", onMsg);
    return () => {
      window.removeEventListener("message", onMsg);
      delete window.__avmIAFill;
    };
  }, []);
  const analizar = async () => {
    if (!form.colonia.trim()) {
      setErrorMsg("Escribe la colonia o fraccionamiento.");
      return;
    }
    const supPrincipal = esTerreno ? parseFloat(form.m2_terreno) : parseFloat(form.m2_construccion);
    if (!supPrincipal || supPrincipal <= 0) {
      setErrorMsg(esTerreno ? "Ingresa los m² de terreno." : "Ingresa los m² de construcción.");
      return;
    }
    setErrorMsg("");
    setEstado("loading");
    try {
      const body = {
        colonia: form.colonia.trim(),
        tipo_inmueble: form.tipo,
        operacion: form.operacion,
        m2_terreno: parseFloat(form.m2_terreno) || 0,
        m2_construccion: parseFloat(form.m2_construccion) || 0,
        recamaras: parseInt(form.recamaras) || 0,
        banos: parseFloat(form.banos) || 0,
        estacionamientos: parseInt(form.estacionamientos) || 0,
        condicion_terreno: form.condicion_terreno || "",
        ciudad: form.ciudad || "",
        estado: form.estado || "",
        latitud: form.latitud || 0,
        longitud: form.longitud || 0,
        comentarios: form.comentarios || ""
      };
      const r = await fetch(`${API}/api/avm-websearch`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      });
      const data = await r.json();
      if (!r.ok) throw new Error(data.detail || "Error en el análisis");
      setResultado(data);
      setEstado("result");
    } catch (e) {
      setErrorMsg(e.message || "No se pudo conectar. Intenta de nuevo.");
      setEstado("error");
    }
  };
  const descargarPDF = async () => {
    if (!resultado) return;
    setPdfLoading(true);
    try {
      // Paso 1: generar PDF en Railway
      const r = await fetch(`${API}/avm-pdf`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          resultado,
          agente: "Agente Broquer®"
        })
      });
      const data = await r.json();
      if (!r.ok) throw new Error(data.detail || "Error generando PDF");

      // Paso 2: obtener bytes del PDF
      const pdfResp = await fetch(`${API}/avm-pdf/${data.token}`);
      if (!pdfResp.ok) throw new Error("No se pudo obtener el PDF");
      const blob = await pdfResp.blob();
      const filename = data.filename || "Estimacion_Valor.pdf";
      if (window.broquerDeliverBlob) {
        await window.broquerDeliverBlob(blob, filename, {
          type: 'application/pdf',
          title: 'Estimación de valor lista',
          text: 'Estimación de valor generada por Broquer'
        });
      } else {
        const blobUrl = URL.createObjectURL(blob);
        window.open(blobUrl, '_blank', 'noopener');
        setTimeout(() => URL.revokeObjectURL(blobUrl), 3000);
      }
    } catch (e) {
      alert("Error al generar PDF: " + (e.message || e));
    } finally {
      setPdfLoading(false);
    }
  };
  const fmtMXN = n => "$" + Math.round(n || 0).toLocaleString("es-MX");
  const confClass = c => c === "alta" ? "ia-conf alta" : c === "media" ? "ia-conf media" : "ia-conf baja";
  const dotColor = imp => imp === "positivo" ? "var(--success)" : imp === "negativo" ? "var(--danger)" : "var(--gray-400)";

  // ── ESTADO: FORMULARIO ──
  if (estado === "idle" || estado === "error") return /*#__PURE__*/React.createElement("div", {
    className: "avm-body"
  }, /*#__PURE__*/React.createElement("div", {
    className: "avm-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "field-row",
    style: {
      marginBottom: 14
    }
  }, /*#__PURE__*/React.createElement(F, {
    label: "Tipo de inmueble"
  }, /*#__PURE__*/React.createElement("select", {
    value: form.tipo,
    onChange: e => u("tipo", e.target.value)
  }, TIPOS.map(t => /*#__PURE__*/React.createElement("option", {
    key: t.id,
    value: t.id
  }, t.label))))), /*#__PURE__*/React.createElement("div", {
    className: "toggle-opt"
  }, /*#__PURE__*/React.createElement("button", {
    className: "toggle-btn" + (form.operacion === "venta" ? " active" : ""),
    onClick: () => u("operacion", "venta")
  }, "Venta"), /*#__PURE__*/React.createElement("button", {
    className: "toggle-btn" + (form.operacion === "renta" ? " active" : ""),
    onClick: () => u("operacion", "renta")
  }, "Renta"))), /*#__PURE__*/React.createElement("div", {
    className: "avm-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "card-label"
  }, "Ubicaci\xF3n"), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Colonia / Fraccionamiento *"
  }, /*#__PURE__*/React.createElement(ColoniaTextInput, {
    value: form.colonia,
    onChange: v => setForm(p => ({
      ...p,
      colonia: v,
      ciudad: "",
      estado: "",
      latitud: 0,
      longitud: 0
    })),
    onSelect: s => setForm(p => ({
      ...p,
      colonia: s.nombre,
      ciudad: s.ciudad || "",
      estado: s.estado || "",
      latitud: s.latitud || 0,
      longitud: s.longitud || 0
    }))
  }))), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 12,
      color: "var(--gray-400)",
      marginTop: -2
    }
  }, "Si la colonia no aparece, intenta con una cercana. A veces los fraccionamientos privados son su propia colonia y a veces pertenecen a una colonia. Si hay dos colonias con el mismo nombre en distintas ciudades, agrega la ciudad para encontrar la correcta (ej. \"Jes\xFAs del Monte, Morelia\")."), form.ciudad ? /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 12,
      color: "var(--gray-400)",
      marginTop: -2
    }
  }, "Ubicaci\xF3n: ", form.ciudad, form.estado ? `, ${form.estado}` : "") : form.colonia.trim().length >= 3 && /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 12,
      color: "var(--warn)",
      marginTop: -2
    }
  }, "Elige una opci\xF3n de la lista para ubicar ciudad y estado autom\xE1ticamente.")), /*#__PURE__*/React.createElement("div", {
    className: "avm-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "card-label"
  }, "Superficies"), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, (esTerreno || esConstruccion) && /*#__PURE__*/React.createElement(F, {
    label: "m\xB2 de terreno"
  }, /*#__PURE__*/React.createElement(NI, {
    value: form.m2_terreno,
    onChange: v => u("m2_terreno", v),
    placeholder: "200"
  })), esConstruccion && /*#__PURE__*/React.createElement(F, {
    label: "m\xB2 construidos *"
  }, /*#__PURE__*/React.createElement(NI, {
    value: form.m2_construccion,
    onChange: v => u("m2_construccion", v),
    placeholder: "200"
  }))), esTerreno && /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Condici\xF3n del terreno"
  }, /*#__PURE__*/React.createElement("select", {
    value: form.condicion_terreno,
    onChange: e => u("condicion_terreno", e.target.value)
  }, /*#__PURE__*/React.createElement("option", {
    value: "plano"
  }, "Plano"), /*#__PURE__*/React.createElement("option", {
    value: "pendiente"
  }, "Con pendiente"), /*#__PURE__*/React.createElement("option", {
    value: "irregular"
  }, "Irregular"))))), esConstruccion && /*#__PURE__*/React.createElement("div", {
    className: "avm-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "card-label"
  }, "Caracter\xEDsticas"), /*#__PURE__*/React.createElement("div", {
    className: "field-row"
  }, /*#__PURE__*/React.createElement(F, {
    label: "Rec\xE1maras"
  }, /*#__PURE__*/React.createElement(NI, {
    value: form.recamaras,
    onChange: v => u("recamaras", v),
    placeholder: "3"
  })), /*#__PURE__*/React.createElement(F, {
    label: "Ba\xF1os"
  }, /*#__PURE__*/React.createElement(NI, {
    value: form.banos,
    onChange: v => u("banos", v),
    placeholder: "2"
  })), /*#__PURE__*/React.createElement(F, {
    label: "Estac."
  }, /*#__PURE__*/React.createElement(NI, {
    value: form.estacionamientos,
    onChange: v => u("estacionamientos", v),
    placeholder: "2"
  })))), /*#__PURE__*/React.createElement("div", {
    className: "avm-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "card-label"
  }, "Comentarios adicionales (opcional)"), /*#__PURE__*/React.createElement("textarea", {
    value: form.comentarios,
    onChange: e => u("comentarios", e.target.value),
    placeholder: "Ej: esquina, vista panor\xE1mica, con bardas, cerca del campo de golf...",
    style: {
      width: "100%",
      padding: "10px 12px",
      background: "var(--paper-2)",
      border: "1px solid rgba(0,0,0,0.1)",
      borderRadius: 10,
      color: "var(--ink)",
      outline: "none",
      fontFamily: "var(--font-sans)",
      fontSize: 13,
      minHeight: 72,
      resize: "vertical"
    }
  })), (estado === "error" || errorMsg) && /*#__PURE__*/React.createElement("div", {
    className: "alert warn",
    style: {
      marginBottom: 12
    }
  }, errorMsg), /*#__PURE__*/React.createElement("button", {
    id: "btn-analizar-ia",
    className: "btn-primary teal",
    onClick: analizar
  }, "Generar estimaci\xF3n de valor"));

  // ── ESTADO: CARGANDO ──
  if (estado === "loading") return /*#__PURE__*/React.createElement("div", {
    className: "avm-body"
  }, /*#__PURE__*/React.createElement("div", {
    className: "avm-card",
    style: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      padding: "22px 18px"
    }
  }, /*#__PURE__*/React.createElement("video", {
    autoPlay: true,
    muted: true,
    loop: true,
    playsInline: true,
    poster: "animacion-broquer.png",
    style: {
      width: "100%",
      maxWidth: 280,
      marginBottom: 14
    }
  }, /*#__PURE__*/React.createElement("source", {
    src: "animacion-broquer.mp4",
    type: "video/mp4"
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 15,
      fontWeight: 700,
      color: "var(--ink)",
      marginBottom: 6
    }
  }, "Buscando comparables"), /*#__PURE__*/React.createElement("div", {
    className: "ia-loading-sub"
  }, "Consultando Lamudi, Vivanuncios, Inmuebles24"), /*#__PURE__*/React.createElement("div", {
    className: "ia-loading-sub",
    style: {
      marginTop: 4
    }
  }, "Esto puede tomar algunos minutos")));

  // ── ESTADO: RESULTADO ──
  if (estado === "result" && resultado) {
    const fmtMXN2 = n => "$" + Math.round(n || 0).toLocaleString("es-MX");
    const comparables = resultado.comparables || [];
    const factores = resultado.factores_ajuste || [];
    const recs = resultado.recomendaciones || [];
    const resumen = resultado.resumen_ejecutivo || "";
    const tipoLabel = form.tipo.charAt(0).toUpperCase() + form.tipo.slice(1);
    return /*#__PURE__*/React.createElement("div", {
      className: "avm-body"
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 10,
        marginTop: 6,
        marginBottom: 14
      }
    }, /*#__PURE__*/React.createElement("button", {
      className: "btn-primary outline",
      style: {
        flex: 1
      },
      onClick: () => {
        setEstado("idle");
        setResultado(null);
        setOpinionMode(false);
      }
    }, "\u2190 Nueva b\xFAsqueda"), /*#__PURE__*/React.createElement("button", {
      className: "btn-primary teal",
      style: {
        flex: 1.4
      },
      disabled: pdfLoading,
      onClick: descargarPDF
    }, pdfLoading ? "Generando PDF…" : "Descargar PDF")), /*#__PURE__*/React.createElement("div", {
      className: "opinion-page"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-header-bar"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-doc-title"
    }, "Estimaci\xF3n de valor"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-meta"
    }, /*#__PURE__*/React.createElement("div", null, new Date().toLocaleDateString("es-MX", {
      year: "numeric",
      month: "long",
      day: "numeric"
    })))), /*#__PURE__*/React.createElement("div", {
      className: "opinion-valor-hero"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-valor-label"
    }, "Valor estimado"), resultado.valor_estimado ? /*#__PURE__*/React.createElement("div", {
      className: "opinion-valor-num"
    }, fmtMXN2(resultado.valor_estimado)) : /*#__PURE__*/React.createElement("div", {
      className: "opinion-valor-num",
      style: {
        fontSize: "1.3rem"
      }
    }, "No fue posible calcular un monto \u2014 revisa el resumen y las recomendaciones abajo")), /*#__PURE__*/React.createElement("div", {
      className: "opinion-section"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-section-title"
    }, "Inmueble sujeto"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-grid"
    }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Tipo"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, tipoLabel)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Operaci\xF3n"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.operacion === "venta" ? "Venta" : "Renta")), form.colonia && /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Colonia"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.colonia)), form.ciudad && /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Ciudad"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.ciudad)), form.estado && /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Estado"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.estado)), parseFloat(form.m2_terreno) > 0 && /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Terreno"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.m2_terreno, " m\xB2")), parseFloat(form.m2_construccion) > 0 && /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-label"
    }, "Construcci\xF3n"), /*#__PURE__*/React.createElement("div", {
      className: "opinion-field-value"
    }, form.m2_construccion, " m\xB2")))), resumen && /*#__PURE__*/React.createElement("div", {
      className: "opinion-section"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-section-title"
    }, "Resumen del an\xE1lisis"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        color: "var(--ink)",
        lineHeight: 1.6,
        textAlign: "justify"
      }
    }, resumen)), comparables.length > 0 && /*#__PURE__*/React.createElement("div", {
      className: "opinion-section"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-section-title"
    }, "Comparables (", comparables.length, ")"), /*#__PURE__*/React.createElement("table", {
      className: "comp-tabla"
    }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("th", null, "#"), /*#__PURE__*/React.createElement("th", null, "Descripci\xF3n"), /*#__PURE__*/React.createElement("th", null, "Sup."), /*#__PURE__*/React.createElement("th", null, "Precio"), /*#__PURE__*/React.createElement("th", null, "$/m\xB2"), /*#__PURE__*/React.createElement("th", null, "Enlace"))), /*#__PURE__*/React.createElement("tbody", null, comparables.slice(0, 8).map((c, i) => /*#__PURE__*/React.createElement("tr", {
      key: i
    }, /*#__PURE__*/React.createElement("td", null, i + 1), /*#__PURE__*/React.createElement("td", {
      style: {
        maxWidth: 240,
        overflow: "hidden",
        textOverflow: "ellipsis"
      }
    }, c.descripcion), /*#__PURE__*/React.createElement("td", null, c.superficie_m2, " m\xB2"), /*#__PURE__*/React.createElement("td", {
      style: {
        fontWeight: 700
      }
    }, fmtMXN2(c.precio)), /*#__PURE__*/React.createElement("td", {
      style: {
        color: "var(--sky-blue-press)",
        fontWeight: 700
      }
    }, fmtMXN2(c.precio_m2)), /*#__PURE__*/React.createElement("td", null, c.url ? /*#__PURE__*/React.createElement("a", {
      href: c.url,
      target: "_blank",
      rel: "noopener noreferrer",
      style: {
        color: "var(--sky-blue-press)",
        textDecoration: "underline"
      }
    }, c.fuente || "Ver") : /*#__PURE__*/React.createElement("span", {
      style: {
        color: "var(--gray-400)"
      }
    }, c.fuente || "—"))))))), recs.length > 0 && /*#__PURE__*/React.createElement("div", {
      className: "opinion-section"
    }, /*#__PURE__*/React.createElement("div", {
      className: "opinion-section-title"
    }, "Recomendaciones clave"), recs.slice(0, 4).map((r, i) => /*#__PURE__*/React.createElement("div", {
      key: i,
      style: {
        display: "flex",
        gap: 8,
        marginBottom: 6,
        fontSize: 12,
        color: "var(--ink)",
        alignItems: "flex-start"
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        color: "var(--sky-blue)",
        fontWeight: 700,
        flexShrink: 0
      }
    }, "\u203A"), /*#__PURE__*/React.createElement("span", {
      style: {
        lineHeight: 1.5
      }
    }, r)))), (resultado.fuentes_consultadas || []).length > 0 && (() => {
      const fc = resultado.firecrawl || {};
      const fuentes = (resultado.fuentes_consultadas || []).filter(f => f.lectura !== "omitido");
      const color = l => l === "bloqueado" ? "var(--danger)" : l === "leído con Firecrawl" ? "var(--sky-blue-press)" : "var(--success)";
      const host = u => {
        try {
          return new URL(u).hostname.replace(/^www\./, "");
        } catch (e) {
          return u || "";
        }
      };
      return /*#__PURE__*/React.createElement("div", {
        className: "opinion-section"
      }, /*#__PURE__*/React.createElement("div", {
        className: "opinion-section-title"
      }, "Fuentes consultadas"), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 12,
          color: "var(--ink)",
          marginBottom: 8,
          lineHeight: 1.5
        }
      }, fc.activo ? /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("strong", null, "Firecrawl activo."), " ", fc.leidas || 0, " p\xE1gina(s) le\xEDda(s) con Firecrawl", fc.cache ? `, ${fc.cache} desde caché` : "", fc.intentos > (fc.leidas || 0) ? `, ${fc.intentos - (fc.leidas || 0)} intento(s) fallido(s)` : "", fc.motivo_no_uso ? ` (no se usó porque ${fc.motivo_no_uso})` : "", ".") : /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("strong", null, "Firecrawl inactivo"), fc.motivo_no_uso ? `: ${fc.motivo_no_uso}` : "", ". Los portales que bloquean a los robots no se pudieron leer.")), fuentes.map((f, i) => /*#__PURE__*/React.createElement("div", {
        key: i,
        style: {
          display: "flex",
          justifyContent: "space-between",
          gap: 10,
          fontSize: 12,
          padding: "5px 0",
          borderTop: i ? "1px solid var(--gray-200)" : "none"
        }
      }, /*#__PURE__*/React.createElement("a", {
        href: f.url,
        target: "_blank",
        rel: "noopener noreferrer",
        style: {
          color: "var(--ink)",
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
          minWidth: 0
        }
      }, f.portal || host(f.url), f.titulo ? ` · ${f.titulo}` : ""), /*#__PURE__*/React.createElement("span", {
        style: {
          color: color(f.lectura),
          fontWeight: 700,
          flexShrink: 0
        }
      }, f.lectura || "bloqueado"))));
    })(), resultado.advertencias && /*#__PURE__*/React.createElement("div", {
      style: {
        background: "var(--warn-soft)",
        borderLeft: "3px solid var(--warn)",
        borderRadius: 8,
        padding: "8px 12px",
        fontSize: 12,
        color: "var(--forest)",
        marginBottom: 14
      }
    }, /*#__PURE__*/React.createElement("strong", null, "Nota:"), " ", resultado.advertencias), /*#__PURE__*/React.createElement("div", {
      style: {
        marginTop: 22,
        paddingTop: 12,
        borderTop: "1px solid var(--gray-200)",
        textAlign: "center",
        fontSize: 10,
        color: "var(--gray-400)",
        letterSpacing: "0.3px"
      }
    }, "Powered by Broquer")));
  }
  return null;
}
// ─── FIN COMPONENTE AvmIA ─────────────────────────────────────

function AVM() {
  const [tab, setTab] = useState(0);
  const [sujeto, setSujeto] = useState({
    tipo: "casa",
    direccion: "",
    colonia: "",
    ciudad: "",
    m2Terreno: "",
    m2Construccion: "",
    recamaras: "",
    banos: "",
    estacionamiento: "",
    nivel: "",
    unidades: "",
    edad: "",
    conservacion: "bueno",
    calidad: "medio"
  });
  const [coloniaObj, setColoniaObj] = useState(null); // {nombre, latitud, longitud}
  const [comps, setComps] = useState([]);
  const [autoComps, setAutoComps] = useState([]);
  const [autoSel, setAutoSel] = useState(new Set());
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const u = (k, v) => setSujeto(p => ({
    ...p,
    [k]: v
  }));
  const campos = CAMPOS[sujeto.tipo] || CAMPOS.casa;

  // Expone window.__avmFill para que Broq pueda llenar el formulario vía postMessage
  useEffect(() => {
    window.__avmFill = data => {
      if (data.tipo_inmueble) setSujeto(p => ({
        ...p,
        tipo: data.tipo_inmueble
      }));
      if (data.colonia) {
        setSujeto(p => ({
          ...p,
          colonia: data.colonia
        }));
        setColoniaObj({
          nombre: data.colonia,
          latitud: null,
          longitud: null
        });
      }
      if (data.ciudad) setSujeto(p => ({
        ...p,
        ciudad: data.ciudad.toLowerCase()
      }));
      if (data.m2_construccion !== undefined) setSujeto(p => ({
        ...p,
        m2Construccion: String(data.m2_construccion)
      }));
      if (data.m2_terreno !== undefined) setSujeto(p => ({
        ...p,
        m2Terreno: String(data.m2_terreno)
      }));
      if (data.recamaras !== undefined) setSujeto(p => ({
        ...p,
        recamaras: String(data.recamaras)
      }));
      if (data.banos !== undefined) setSujeto(p => ({
        ...p,
        banos: String(data.banos)
      }));
      if (data.edad !== undefined) setSujeto(p => ({
        ...p,
        edad: String(data.edad)
      }));
      if (data.direccion) setSujeto(p => ({
        ...p,
        direccion: data.direccion
      }));
      setTab(0);
    };
    const onMsg = e => {
      if (e.data && e.data.tipo === 'llenar_avm') window.__avmFill(e.data);
      // opinion_valor_web -> activa pestaña IA
      if (e.data && e.data.tipo === 'opinion_valor_web') {
        setTab(3);
        if (window.__avmIAFill) {
          window.__avmIAFill(e.data);
          setTimeout(() => {
            const btn = document.getElementById('btn-analizar-ia');
            if (btn) btn.click();
          }, 400);
        }
      }
    };
    window.addEventListener('message', onMsg);
    return () => {
      window.removeEventListener('message', onMsg);
      delete window.__avmFill;
    };
  }, []);
  const addComp = () => setComps(p => [...p, {
    id: Date.now(),
    precio: "",
    m2Construccion: "",
    m2Terreno: "",
    recamaras: "",
    banos: "",
    estacionamiento: "",
    edad: "",
    conservacion: "bueno",
    calidad: "medio",
    mismaZona: "si"
  }]);
  const removeComp = id => setComps(p => p.filter(c => c.id !== id));
  const updateComp = (id, k, v) => setComps(p => p.map(c => c.id === id ? {
    ...c,
    [k]: v
  } : c));
  const buscarComparables = useCallback(async () => {
    if (!coloniaObj) {
      setError("Selecciona una colonia del listado primero.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const res = await fetch(`${API}/api/comparables-cercanos`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          latitud: coloniaObj.latitud,
          longitud: coloniaObj.longitud,
          tipo: sujeto.tipo,
          radio_km: 2.0,
          max_resultados: 15
        })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Error");
      setAutoComps(data.comparables || []);
      setAutoSel(new Set());
      if (!(data.comparables || []).length) setError("No encontramos propiedades cercanas. Prueba aumentando el radio o agrega comparables manualmente.");
    } catch {
      setError("No se pudo conectar. Intenta más tarde.");
    } finally {
      setLoading(false);
    }
  }, [coloniaObj, sujeto.tipo]);
  const toggleAutoComp = i => setAutoSel(p => {
    const n = new Set(p);
    n.has(i) ? n.delete(i) : n.add(i);
    return n;
  });
  const allComps = useMemo(() => {
    const auto = [...autoSel].map(i => ({
      ...autoComps[i],
      id: `auto_${i}`,
      mismaZona: "si"
    }));
    return [...auto, ...comps];
  }, [autoSel, autoComps, comps]);
  const result = useMemo(() => {
    const m2c = pf(sujeto.m2Construccion),
      m2t = pf(sujeto.m2Terreno),
      edad = pf(sujeto.edad);
    const esTerreno = sujeto.tipo === "terreno";
    const vidaUtil = esTerreno ? 0 : 70;
    const analyzed = allComps.filter(c => pf(c.precio) > 0 && pf(c.m2Construccion) > 0).map(c => {
      const vum = pf(c.precio) / pf(c.m2Construccion);
      const factors = calcFactors(sujeto, c);
      return {
        ...c,
        vum,
        factors,
        vHomol: vum * factors.fResultante
      };
    });
    const analyzedT = esTerreno ? allComps.filter(c => pf(c.precio) > 0 && pf(c.m2Terreno) > 0).map(c => ({
      ...c,
      vumT: pf(c.precio) / pf(c.m2Terreno)
    })) : [];
    const promHomol = analyzed.length > 0 ? analyzed.reduce((s, c) => s + c.vHomol, 0) / analyzed.length : 0;
    const promHomolT = analyzedT.length > 0 ? analyzedT.reduce((s, c) => s + c.vumT, 0) / analyzedT.length : 0;
    const valorMercado = esTerreno ? promHomolT * m2t : promHomol * m2c;
    const minH = analyzed.length > 0 ? Math.min(...analyzed.map(c => c.vHomol)) : 0;
    const maxH = analyzed.length > 0 ? Math.max(...analyzed.map(c => c.vHomol)) : 0;
    const valorMin = minH * m2c,
      valorMax = maxH * m2c;
    const vrnUnit = CALIDAD_VRN[sujeto.calidad] || 11500;
    const fec = rossHeidecke(edad, vidaUtil, sujeto.conservacion);
    const vnrTotal = vrnUnit * m2c * fec;
    let terrenoUnit = 0;
    if (analyzed.length > 0) {
      const le = analyzed.filter(c => pf(c.m2Terreno) > 0).map(c => {
        const cv = pf(c.m2Construccion) * vrnUnit * rossHeidecke(pf(c.edad), vidaUtil, c.conservacion);
        return Math.max(0, pf(c.precio) * 0.95 - cv) / pf(c.m2Terreno);
      });
      if (le.length > 0) terrenoUnit = le.reduce((a, b) => a + b, 0) / le.length;
    }
    if (terrenoUnit <= 0) terrenoUnit = 5000 * ({
      lujo: 1.4,
      bueno: 1.1,
      medio: 0.85,
      economico: 0.6
    }[sujeto.calidad] || 1);
    const valorTerreno = terrenoUnit * m2t;
    const valorFisico = valorTerreno + vnrTotal;
    const rentaBruta = vrnUnit * fec * 0.005 * m2c;
    const valorCapitalizacion = rentaBruta * 0.86 * 12 / 0.045;
    const nComps = esTerreno ? analyzedT.length : analyzed.length;
    let confianza = "baja",
      confianzaColor = "var(--danger)";
    if (nComps >= 5) {
      confianza = "alta";
      confianzaColor = "var(--success)";
    } else if (nComps >= 3) {
      confianza = "media";
      confianzaColor = "var(--warn)";
    }
    const dispersion = promHomol > 0 && analyzed.length > 1 ? (maxH - minH) / promHomol * 100 : 0;
    return {
      analyzed,
      analyzedT,
      promHomol,
      promHomolT,
      valorMercado,
      valorMin,
      valorMax,
      vrnUnit,
      fec,
      vnrTotal,
      terrenoUnit,
      valorTerreno,
      valorFisico,
      rentaBruta,
      valorCapitalizacion,
      nComps,
      confianza,
      confianzaColor,
      dispersion
    };
  }, [sujeto, allComps]);
  return /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: "var(--font-sans)",
      background: "var(--paper)",
      minHeight: "100vh"
    }
  }, /*#__PURE__*/React.createElement(AvmIA, null));
}
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render( /*#__PURE__*/React.createElement(AVM, null));
