/* Regenerate after editing the inline JSX in avm.html.
 * npm install --prefix /tmp/broquer-build @babel/standalone@7.23.5
 * BABEL_MODULE=/tmp/broquer-build/node_modules/@babel/standalone node scripts/compile_avm.cjs
 * Babel is a build dependency only; the browser uses local React 18.2.0.
 */
const fs = require('node:fs');
const path = require('node:path');
const babel = require(process.env.BABEL_MODULE || '@babel/standalone');
if (babel.version !== '7.23.5') throw Error('Use @babel/standalone 7.23.5 for reproducible output');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'avm.html'), 'utf8').match(/<script type="text\/babel">([\s\S]*?)<\/script>/)?.[1];
if (!source) throw Error('AVM JSX source was not found');
const result = babel.transform(source, { presets: ['react'], comments: true }).code;
fs.writeFileSync(path.join(root, 'avm-runtime.js'), '// Generated by scripts/compile_avm.cjs from avm.html. Do not edit directly.\n' + result + '\n');
